export default {
    "base": "http://mabnasys.com/api/", //"http://www.mabnasys.com/api/",
    "signalrBase": "http://mabnasys.com/",
    "signalrHub": "baseHub",
    "findFavServices": "account-course/find-student/",
    "findServices": "course/find-by-account/",
    "findAllServices": "course/all/",
    "findAllByAccount": "course/find-all-by-account",
    "findBookedServices": "booking/find-student-bookings-by-status/1/",
    "findOnGoingServices": "booking/find-student-bookings-by-status/2/",
    "findBookingList": "booking/find-teacher-pending-bookings",
    "findExpertPendingList": "booking/find-teacher-bookings-by-status/2",
    "findExpertHistory": "booking/find-teacher-bookings-by-status/3",
    "findUserHistory": "booking/find-student-bookings-by-status/3",
    "bookNow": "booking/book/",
    "cancelBooking": "booking/cancel/",
    "acceptBooking": "booking/accept/",
    "balance": "account-credit/balance/",
    "profile": "account/account/",
    "updateProfile": "account/update/",
    "deleteService": "account-course/delete/",
    "registerService": "account-course/register/",
    "CreditPackages": "credit/all/",
    "job": "job/index.json",
    "search": "search/",
    "chat": "chat-message/find-by-booking-id/",
    "send": "chat-message/send",
    "findBooking": "/booking/retrieve/",
    "signalrEvents": {
        onTeacherBookingAccepted: "onTeacherBookingAccepted",
        onStudentBookingAccepted: "onStudentBookingAccepted",
        onBookingCompleted: "onBookingCompleted",
        onBooking: "onBooking",
        onReceiveMessage: "ReceiveMessage"
    }
}